version: "3.8"
services:
  ideamart:
    build: .
    container_name: "ideamart"
    network_mode: host
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongo-db:/data/db
    network_mode: host
volumes:
  mongo-db: